"""Hello GitHub Models — a minimal example of calling an AI model via GitHub Models."""

import json
import os
import sys
from datetime import datetime, timezone
from openai import OpenAI


def call_github_model() -> str:
    """Call a GitHub-hosted model and return the response text."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Error: GITHUB_TOKEN environment variable is required.", file=sys.stderr)
        sys.exit(1)

    client = OpenAI(
        base_url="https://models.inference.ai.azure.com",
        api_key=token,
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "system",
                "content": "You are a friendly assistant. Keep responses to 2-3 sentences.",
            },
            {
                "role": "user",
                "content": "Say hello world in a creative and fun way! Include an emoji.",
            },
        ],
        temperature=0.9,
        max_tokens=150,
    )

    return response.choices[0].message.content.strip()


def generate_html(greeting: str) -> str:
    """Generate a simple HTML page with the greeting."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello GitHub Models</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #fff;
            padding: 2rem;
        }}
        .card {{
            background: rgba(255, 255, 255, 0.15);
            backdrop-filter: blur(10px);
            border-radius: 1.5rem;
            padding: 3rem;
            max-width: 600px;
            text-align: center;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
        }}
        h1 {{ font-size: 2rem; margin-bottom: 1.5rem; }}
        .greeting {{
            font-size: 1.25rem;
            line-height: 1.6;
            margin-bottom: 2rem;
            padding: 1.5rem;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 1rem;
        }}
        .meta {{
            font-size: 0.85rem;
            opacity: 0.8;
        }}
        a {{ color: #fff; }}
    </style>
</head>
<body>
    <div class="card">
        <h1>Hello GitHub Models</h1>
        <div class="greeting">{greeting}</div>
        <p class="meta">
            Generated by <a href="https://github.com/marketplace/models">GitHub Models</a>
            (gpt-4o-mini)<br>
            Last updated: {timestamp}
        </p>
    </div>
</body>
</html>"""


def main():
    print("Calling GitHub Models (gpt-4o-mini)...")
    greeting = call_github_model()
    print(f"Response: {greeting}")

    html = generate_html(greeting)

    output_path = os.path.join("docs", "index.html")
    os.makedirs("docs", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)
    print(f"Written to {output_path}")

    # Also write the raw response as JSON for programmatic use
    data = {
        "greeting": greeting,
        "model": "gpt-4o-mini",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    json_path = os.path.join("docs", "latest.json")
    with open(json_path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Written to {json_path}")


if __name__ == "__main__":
    main()
